### ISSUE TITLE
项目介绍的网站变了吗？

### ISSUE THREAD

**Issue by felicitia** [white-cat/ThinkAndroid#1]
你好，thinkandroid.cn打开根本不是项目的网站啊，请问项目主页是否变更了？谢谢！

**Comment by Soperf** [comment]
打不开，没看到换主页的消息，https://github.com/white-cat/ThinkAndroid

2014-10-27 15:26 GMT+08:00 Yixue Zhao notifications@github.com:

> 你好，thinkandroid.cn打开根本不是项目的网站啊，请问项目主页是否变更了？谢谢！
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/white-cat/ThinkAndroid/issues/1.

## 

fangxiaopeng
email：soperfang@gmail.com
phone:15558186698

**Comment by e-cloud** [comment]
看来这个项目已经断了

**Comment by hloong** [comment]
我去群里问了下，是停止维护了……
